### ISSUE TITLE
ValidationError: Not catching by global exception filter

### ISSUE THREAD

**Issue by emonorg** [emonorg/ayberk-server#1]
In request `/operators/grant-privilege` with body: 
```JSON
{
    "operatorId": "6331f66cc049110957606af2",
    "domain": "foo",
    "actions": {
        "create": false,
        "read": true,
        "update": true,
        "delete": true
    }
}
```
The `domain` field with value `foo` is invalid and this requests causes 500 error which is not appropriate.  
Logs:
```
[Nest] 63330  - 26/09/2022, 21:41:54   ERROR [ExceptionsHandler] Privilege validation failed: domain: `foo` is not a valid enum value for path `domain`.
ValidationError: Privilege validation failed: domain: `foo` is not a valid enum value for path `domain`.
    at model.Document.invalidate (/Users/emon/tmp/Ayberk/ayberk/node_modules/mongoose/lib/document.js:3054:32)
    at /Users/emon/tmp/Ayberk/ayberk/node_modules/mongoose/lib/document.js:2842:17
    at /Users/emon/tmp/Ayberk/ayberk/node_modules/mongoose/lib/schematype.js:1349:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by hadibavili** [comment]
You can track issue with this [PR](https://github.com/emonorg/ayberk-server/pull/3)

**Comment by emonorg** [comment]
Also, it is needed to return the valid values of enum as an array.
